import './globals.css'
import Navigation from '@/components/Navigation'
export const metadata = {
  title: 'Salsabeel Alzaqa',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Navigation>{children}</Navigation></body>
    </html>
  )
}
